# Generated by Django 6.0.1 on 2026-09-14 17:32

import datetime
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
            ],
        ),
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do EPI')),
                ('periodicidade_valor', models.PositiveIntegerField(default=1, verbose_name='Quantidade de tempo')),
                ('periodicidade_unidade', models.CharField(choices=[('DIAS', 'Dias'), ('SEMANAS', 'Semanas'), ('MESES', 'Meses'), ('ANOS', 'Anos')], default='MESES', max_length=10, verbose_name='Unidade de tempo')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField(default=datetime.date.today, verbose_name='Data de Entrega')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_vinculados', to='core.colaborador', verbose_name='Colaborador')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.epi', verbose_name='EPI')),
            ],
            options={
                'verbose_name': 'Registro de EPI',
                'verbose_name_plural': 'Registros de EPIs',
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='core.setor', verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Um usuário com esse nome já existe.'}, help_text='Obrigatório. 150 caracteres ou menos. Letras, números, espaços e @/./+/-/_ apenas.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Informe um nome de usuário válido. Pode conter letras, números, caracteres @/./+/-/_ e espaços.', regex='^[\\w.@+-]+(?: [\\w.@+-]+)*$')], verbose_name='nome de usuário')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Extintor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga', models.CharField(choices=[('PO_QUIMICO_ABC', 'Pó Químico ABC'), ('PO_QUIMICO_BC', 'Pó Químico BC'), ('CO2', 'CO₂'), ('AGUA', 'Água Pressurizada'), ('ESPUMA', 'Espuma Mecânica'), ('ACETATO', 'Acetato de Potássio')], help_text='Ex: Pó Químico, CO2, Água Pressurizada, Espuma Mecânica', max_length=50, verbose_name='Carga (Agente Extintor)')),
                ('tipo', models.CharField(choices=[('ABC', 'ABC'), ('BC', 'BC'), ('A', 'A'), ('K', 'K')], help_text='Ex: ABC, BC, A, K', max_length=10, verbose_name='Tipo (Classe)')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número do Extintor')),
                ('data_vistoria', models.DateField(verbose_name='Data da ÚLTIMA Vistoria')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento/Recarga')),
                ('situacao', models.CharField(choices=[('OK', 'Em Dia / Regular'), ('PENDENTE', 'Necessita Inspeção'), ('VENCIDO', 'Vencido'), ('MANUTENCAO', 'Em Manutenção')], default='OK', max_length=15, verbose_name='Status de Uso')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='extintores/', verbose_name='Foto do Extintor')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extintores', to='core.setor', verbose_name='Setor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('numero', 'setor'), name='unique_extintor_numero_por_setor')],
            },
        ),
    ]
